# Generated by Django 4.2.6 on 2023-11-01 20:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0002_category_listing"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="watchlist",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="listing",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
